name: 🚀 Deploy backend on push branch main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code on branch main
        uses: actions/checkout@v1

      - name: 🐧 Deploy to linux server
        uses: appleboy/scp-action@v0.1.4

        env:
          HOST: ${{ secrets.HOSTNAME }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          PASSPHRASE: ${{ secrets.PASSWORD }}
        with:
          source: '.'
          target: '/var/www/app5/simakdajknbok_2024'

      - name: 🪟 Deploy to windows server
        uses:  appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.HOSTNAME_WINDOWS }}
          username: ${{ secrets.USERNAME_WINDOWS }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY_WINDOWS }}
          passphrase: ${{ secrets.PASSWORD_WINDOWS }}
          script: |
            cd C:\aplikasi\app5\action && ./jknbok_2024.bat
